### PR TITLE
Hotfix/get charts working again

### PR DESCRIPTION
**Pull request by TJMdeveloper**
I was working with Echo3Charts back in January and couldn't get them to work.  I just now was able to find time to give back my changes so others can use them.   You can test this out by using the instructions in the readme on my fork to test your current echo3chart application out with the echo-3.1.0 (master) code.  You can't see the test app working with the pie chart.   Once you apply these fixes then the pie chart will start working again.

### CODE REVIEW

**Comment by bentolor** [comment]
Thanks for your contribution @maciakt ! Glad to hear you were able to work out the issue.

Unfortunately you reformatted the code, which gives me a very hard time for reading & reviewing your patch (as you can see [here](https://github.com/echo3/echo3chart/pull/1/commits/35cd95d50ac1b08edc081363853598d47e466d11)). Can you point out the changes you made?

**Comment by TJMdeveloper** [comment]
Yes I will pull the original, apply my changes and then make a new PR.
Sorry about that.

I will probably get to it in the next day or two.

Thanks.

T.J.

**Comment by TJMdeveloper** [comment]
@bentolor - updated file... i can see the diff clearly here: https://github.com/echo3/echo3chart/pull/1/files

**Comment by bentolor** [comment]
Thanks @maciakt! Already reviewing it and LGTM. Much better to see your change. I'll squash-merge your changes to keep the clarity.

**Comment by TJMdeveloper** [comment]
@bentolor  - great!  doesn't seem like too much activity has happened with echo3 over the last year or two but I used it for an app this year and took advantage of the charts :)

**Comment by bentolor** [comment]
Unfortunately the project is more or less stale, though I still think it has a superior design in contrast to other current Java web frameworks.

**Comment by TJMdeveloper** [comment]
Yeah I had used echo2 for apps from about 2008 - 2011.  I had the
opportunity to use echo3 for an app earlier this year and it stood up
pretty well.  There are a few things I had trouble with (like components
from epng that were not available in echo3) but for the most part echo3
performed well. If I continue working in it and find ways for improvements
I will be happy to contribute back to the projects related to echo3 and all
of its components.

**Pull request merged**
